services:
  # Backend API server
  backend:
    build:
      context: src/backend
      dockerfile: Dockerfile
    container_name: vocab-backend
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app:/app/src
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload

  # Frontend development server
  frontend:
    build:
      context: src/frontend
      dockerfile: Dockerfile
    container_name: vocab-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  # Test runner
  tests:
    build:
      context: .
      dockerfile: tests.Dockerfile
    container_name: vocab-tests
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app:/app/src
    command: python -m pytest src/backend/tests/ -v